version: "3.2"
services:
  flasky:
    build: .
    ports:
      - "8000:5000"
    networks:
      - backend
    env_file: .env
    environment:
      DATABASE_URL: "mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_NAME}"
    restart: always
    container_name: flasky
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env
    restart: always
    expose:
      - "3306"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
networks:
  backend:
volumes:
    data:
